"""new fields in user model

Revision ID: 320209d15d40
Revises: ed1a4885595c
Create Date: 2018-12-03 16:33:25.564076

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '320209d15d40'
down_revision = 'ed1a4885595c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
